# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    env_file: .env
    volumes:
      - .:/app
  remote-interpreter:
    build: *dockerfile-dev-build
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    command:
      [
        "./scripts/start-development.sh",
      ]
    healthcheck:
      test: [ "CMD-SHELL", "python manage.py health_check -s readiness --skip-checks" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
  app-production:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_VITE_DEBUG: "False"
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
  app-production-ssr:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    depends_on:
      frontend-ssr:
        condition: service_started
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_VITE_DEBUG: "False"
      INERTIA_SSR_ENABLED: "True"
      INERTIA_SSR_URL: "http://frontend-ssr:3000"
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
  frontend-ssr:
    build:
      context: .
      dockerfile: Dockerfile.frontend-ssr
    environment:
      NODE_PORT: 3000

networks:
  default: # "default" name is important because it's automatically used by all services. Check out: https://stackoverflow.com/a/78030885
    name: shared-compose-network
